fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /admin





